CREATE TABLE `dm_record` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `health_id` int(10) unsigned DEFAULT '0' COMMENT '健康管理号',
  `is_diabetes` smallint(5) unsigned DEFAULT '0' COMMENT '是否诊断为糖尿病',
  `fasting_blood_glucose` float(5,2) DEFAULT '0.00' COMMENT '空腹血糖',
  `postprandial_blood_glucose` float(5,2) DEFAULT '0.00' COMMENT '餐后血糖',
  `anytime_blood_glucose` float(5,2) DEFAULT '0.00' COMMENT '任意时间血糖',
  `diabetes_type` smallint(5) unsigned DEFAULT '0' COMMENT '糖尿病类型',
  `is_ketoacidosis` smallint(5) unsigned DEFAULT '0' COMMENT '是否酮症酸中毒病发症',
  `ketoacidosis_frequency` smallint(5) unsigned DEFAULT '0' COMMENT '酮症酸中毒病发症频率',
  `ketoacidosis_reason` varchar(255) DEFAULT '' COMMENT '酮症酸中毒病发症理由',
  `is_hypoglycemia` smallint(5) unsigned DEFAULT '0' COMMENT '是否低血糖',
  `hypoglycemia_frequency` smallint(5) unsigned DEFAULT '0' COMMENT '低血糖发生频率',
  `hypoglycemia_reason` varchar(255) DEFAULT '' COMMENT '低血糖发生原因',
  `hypoglycemia_severity` smallint(5) unsigned DEFAULT '0' COMMENT '低血糖严重程度',
  `is_cerebrovascular` smallint(5) unsigned DEFAULT '0' COMMENT '是否脑血管病变',
  `is_cardiovascular` smallint(5) unsigned DEFAULT '0' COMMENT '是否心血管病变',
  `is_peripheral_vascular` smallint(5) unsigned DEFAULT '0' COMMENT '是否外周血管病变',
  `is_nephrosis` smallint(5) unsigned DEFAULT '0' COMMENT '是否肾病病变',
  `is_fundus_lesions` smallint(5) unsigned DEFAULT '0' COMMENT '是否眼底病变',
  `is_peripheral_neuropathy` smallint(5) unsigned DEFAULT '0' COMMENT '是否周围神经病变',
  `is_diabetic_foot` smallint(5) unsigned DEFAULT '0' COMMENT '糖尿病足',
  `associated_diseases` varchar(255) DEFAULT '' COMMENT '伴发疾病',
  `work_density` smallint(5) unsigned DEFAULT '0' COMMENT '劳动强度',
  `diet` float(5,2) DEFAULT '0.00' COMMENT '主食',
  `vegetables` float(5,2) DEFAULT '0.00' COMMENT '蔬菜',
  `milk` float(5,2) DEFAULT '0.00' COMMENT '牛奶',
  `egg` smallint(5) unsigned DEFAULT '0' COMMENT '鸡蛋',
  `meet` float(5,2) DEFAULT '0.00' COMMENT '肉类',
  `bean` float(5,2) DEFAULT '0.00' COMMENT '豆类',
  `oil` float(5,2) DEFAULT '0.00' COMMENT '油',
  `salt` float(5,2) DEFAULT '0.00' COMMENT '盐',
  `sports_type` smallint(5) unsigned DEFAULT '0' COMMENT '运动方式',
  `sports_intensity` smallint(5) unsigned DEFAULT '0' COMMENT '运动强度',
  `sports_time` smallint(8) unsigned DEFAULT '0' COMMENT '运动时长',
  `sports_frequency` smallint(5) unsigned DEFAULT '0' COMMENT '运动频率',
  `is_smoke` smallint(5) unsigned DEFAULT '0' COMMENT '是否吸烟',
  `smoke_num` smallint(5) unsigned DEFAULT '0' COMMENT '吸烟量',
  `is_drink` smallint(5) unsigned DEFAULT '0' COMMENT '是否饮酒',
  `drink_num` smallint(5) unsigned DEFAULT '0' COMMENT '饮酒量',
  `high_blood_pressure` smallint(8) unsigned DEFAULT '0' COMMENT '血压高压',
  `low_blood_pressure` smallint(8) unsigned DEFAULT '0' COMMENT '血压低压',
  `blood_pressure_addr` smallint(5) unsigned DEFAULT '0' COMMENT '血压测量地点',
  `blood_sugar_2` float(5,2) DEFAULT '0.00' COMMENT '餐后两小时血糖',
  `hbalc` float(5,2) DEFAULT '0.00' COMMENT 'hbalc',
  `tg` float(5,2) DEFAULT '0.00' COMMENT 'tg',
  `ldl_c` float(5,2) DEFAULT '0.00' COMMENT 'ldl_c',
  `hdl_c` float(5,2) DEFAULT '0.00' COMMENT 'hdl_c',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_health_id` (`health_id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8